# Important Concepts

# 1. Forming an array
   ### asanyarray,np.array,np.asarray,np.array(np.mat([list]))

## 2. Arange and linspace
   ### arange - toget data in steps, linspace- to create data b/w the limits in certain frequency

## 3. diagonal matrix, identity matrix, triangular matrix and dependency of k on them
   ### if k factor is present then remove k columns and form the nearest square matrix in the array and form the array

## 4. slicing and indexing

## 5. Using np.random package for generating random integers and array

## 6. Reshaping function to reeshape the data generated through arange or linspace or random package

## 7. Creating a required matrix shape to generate one's or zeros

   ### creating a 1d array is also called as vector

# 8. Difference between Max()[element with high value in arr] and argmax()[position with high value will be returned based on axis]

# 9. Subsetting ( giving condition on top of matrix - eg: mat>50 )

# Numpy Array

In [1]:
import numpy as np
np.array(["vbhvh", 2, 3]) # Array from a list

array(['vbhvh', '2', '3'], dtype='<U5')

# Numpy array declaration and conversion through different functions :-

1. np.array
2. np.array(np.mat)
3. np.asarray
4. np.asanyarray

## Matrix is a subset of an Array but viceversa is wrong

In [2]:
#Upcasting:

In [3]:
np.array([1, 2, 3.0]) # numpy will upcast the data automatically

array([1., 2., 3.])

In [4]:
#two dimensions

In [5]:
 np.array([[1, 2], [3, 4]]) ## 2x2 matrix , 2 dimensional matrix

array([[1, 2],
       [3, 4]])

In [6]:
#Minimum dimensions 2:

In [7]:
np.array([1, 2, 3], ndmin=5) # actually its 1D but converted to 5 dimension

array([[[[[1, 2, 3]]]]])

In [8]:
#dtype

In [9]:
 np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [10]:
#Data-type consisting of more than one element:

In [11]:
np.array([(1,2),(3,4)]) # even on passsing as tuples it will take as an array but it will be helpful fo define datatypes

array([[1, 2],
       [3, 4]])

In [20]:
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [21]:
(x[1,0])

3

In [11]:

#Creating an array from sub-classes:

In [13]:
np.array(np.mat([[1, 2],[4,7]]))

array([[1, 2],
       [4, 7]])

In [17]:
np.mat(np.array([[1, 2],[4,7]]))

matrix([[1, 2],
        [4, 7]])

In [14]:
np.mat('1 2; 3 4') ## strings can be converted to a matrix

matrix([[1, 2],
        [3, 4]])

# numpy.asarray

In [16]:
#Convert the input to an array.

In [18]:
#Convert a list into an array:

In [27]:
 a = [1, 2]
type(a)

list

In [25]:
type(np.asarray(a))

numpy.ndarray

In [31]:
a = np.array([1, 2]) #Existing arrays are not copied
type(a)

numpy.ndarray

In [42]:
np.asarray((1,2))

array([1, 2])

In [25]:
#If dtype is set, array is copied only if dtype does not match:

In [24]:
a = np.array([1, 2], dtype=np.float32)
a

array([1., 2.], dtype=float32)

In [25]:
np.asarray([1,2]) is a

False

In [26]:
np.asarray([1,2])

array([1, 2])

In [29]:
np.asarray(a, dtype=np.float64) is a

False

In [29]:
# ndarray subclasses are not passed through

In [23]:
issubclass(np.matrix, np.ndarray)

True

In [48]:
a = np.matrix([[1, 2]])
np.asanyarray(a)


matrix([[1, 2]])

In [49]:
np.asarray(a) is a

False

In [50]:
np.asanyarray(a) is a

True

In [51]:
type(np.asarray(a))

numpy.ndarray

# numpy.asanyarray

### If the data is already available in any of the forms or subclasses of an array then there is no meaning in implementing the asanyarray function

In [50]:
a = [1, 2]
np.asanyarray(a)

array([1, 2])

In [17]:
a = np.matrix([1, 2])
a

matrix([[1, 2]])

In [18]:
np.asanyarray([1,2]) is a

False

In [19]:
np.array(a, copy=True)  

array([[1, 2]])

In [20]:
#Create an array x, with a reference y and a copy z:

In [2]:
x = np.array([1, 2, 3])
x
x.shape

(3,)

In [39]:
y = x # shallow copy ## Here both x and y will point to same location and even on changing x, y also will change

In [40]:
z = np.copy(x) #deep copy ## x and z will not point to same location and new loc will be created # 

In [41]:
z[0] = 100
z

array([100,   2,   3])

In [36]:
x

array([1, 2, 3])

In [42]:
id(x[0])

140338861803376

In [43]:
id(y[0])

140338861803216

In [44]:
id(x) 

140338593443072

In [45]:
id(y)

140338593443072

# numpy.fromfunction

# Dimensions are different from rows and columns

In [58]:
#Construct an array by executing a function over each coordinate.

In [46]:
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int) # fromfunction is inbuilt in numpy

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [66]:
np.fromfunction(lambda i, j: i * j, (3, 3), dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [68]:
np.fromfunction(lambda i, j, k : i * j * k, (3, 3, 3), dtype=int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 1, 2],
        [0, 2, 4]],

       [[0, 0, 0],
        [0, 2, 4],
        [0, 4, 8]]])

In [70]:
np.fromfunction(lambda i, j, k, m: i * j * k * m, (3, 3, 3, 3), dtype=int) # as this 4D, we can assume that

# 3*(3,3,3) [ three 3d matrices are formed ]

array([[[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  1,  2],
         [ 0,  2,  4]],

        [[ 0,  0,  0],
         [ 0,  2,  4],
         [ 0,  4,  8]]],


       [[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 0,  0,  0],
         [ 0,  2,  4],
         [ 0,  4,  8]],

        [[ 0,  0,  0],
         [ 0,  4,  8],
         [ 0,  8, 16]]]])

In [61]:
#Create a new 1-dimensional array from an iterable object.

# Goal is to convert to an array from all these through inbuilt functions

In [50]:
iterable = (x*x for x in range(5))
iterable

<generator object <genexpr> at 0x7fa33805f5f0>

In [51]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [52]:
#A new 1-D array initialized from text data in a string

In [57]:
a = np.fromstring('234 234',sep=' ')
a

array([234., 234.])

In [58]:
np.fromstring('1, 2', dtype=int, sep=',')

array([1, 2])

In [59]:
# How to create create a record array from a (flat) list of arrays

In [60]:
x1=np.array([1,2,3,4])

In [61]:
x2=np.array(['a','dd','xyz','12'])

In [62]:
x3=np.array([1.1,2,3,4])
x4=np.array([1.1,2,3,4])
type(x4)

numpy.ndarray

In [63]:
r = np.core.records.fromarrays([x1,x2,x3,x4],names='a,b,c,d') ## will store as records
r 

rec.array([(1, 'a', 1.1, 1.1), (2, 'dd', 2. , 2. ), (3, 'xyz', 3. , 3. ),
           (4, '12', 4. , 4. )],
          dtype=[('a', '<i8'), ('b', '<U3'), ('c', '<f8'), ('d', '<f8')])

In [64]:
print(r[1]["a"])

2


In [130]:
x1[1]

2

# data types

In [120]:
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)
print("Type/Class of this object:",type(arr))
print("Here is the vector\n--------------------\n",arr)

Type/Class of this object: <class 'numpy.ndarray'>
Here is the vector
--------------------
 [1 2 3]


In [121]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array


Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int64


In [122]:
my_mat = [[1.1,2,3],[4,5.2,6],[7,8.3,9]]
mat = np.array(my_mat)
print("Data type of the modified matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array
print("\n\nEven tuples can be converted to ndarrays...")


Data type of the modified matrix: float64


Even tuples can be converted to ndarrays...


In [111]:
b = np.array([(1.5,2,3), (4,5,6)])
print("We write b = np.array([(1.5,2,3), (4,5,6)])")
print("Matrix made from tuples, not lists\n---------------------------------------")
print(b)

We write b = np.array([(1.5,2,3), (4,5,6)])
Matrix made from tuples, not lists
---------------------------------------
[[1.5 2.  3. ]
 [4.  5.  6. ]]


# arange and linspace

## Range: Integer dataset
## arange : integer and float will be accessed as data step size

In [127]:
print("A series of numbers:",type(np.arange(5,16)))
np.arange(5,16,2.3)# A series of numbers from low to high

A series of numbers: <class 'numpy.ndarray'>


array([ 5. ,  7.3,  9.6, 11.9, 14.2])

In [128]:
list(range(5,16,2))

[5, 7, 9, 11, 13, 15]

In [129]:
list(range(50,-1,5))

[]

In [135]:
print("Numbers spaced apart by 2:",np.arange(50,-1,5)) # Numbers spaced apart by 2

Numbers spaced apart by 2: []


In [131]:
print("Numbers spaced apart by float:",np.arange(0,11,2.5)) # Numbers spaced apart by 2.5

Numbers spaced apart by float: [ 0.   2.5  5.   7.5 10. ]


In [132]:
print("Every 5th number from 50 in reverse order\n",np.arange(5.0,-1,-5))

Every 5th number from 50 in reverse order
 [5. 0.]


# Difference between Arange and linspace
## Arange: with generate data based on stepsize by excluding some values
## linspace: with generate the data or samples between the two limits based on the frequency given (upper bound is also considered)

In [134]:
print("21 linearly spaced numbers between 1 and 5\n--------------------------------------------")
print((np.linspace(1,5,50)))

21 linearly spaced numbers between 1 and 5
--------------------------------------------
[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


# Matrix creation

In [136]:
print("Vector of zeroes\n---------------------")
print(np.zeros(5))

Vector of zeroes
---------------------
[0. 0. 0. 0. 0.]


In [139]:
print("Matrix of zeroes\n--------------------")
print(np.zeros((3,4))) # Notice Tuples

Matrix of zeroes
--------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [127]:
print("Vector of ones\n---------------------")
print(np.ones(5))

Vector of ones
---------------------
[1. 1. 1. 1. 1.]


In [140]:
print("Matrix of ones\n---------------------")
print(np.ones((5,2,8))) # Note matrix dimension specified by Tuples


Matrix of ones
---------------------
[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]]


In [147]:
print("Matrix of 5's\n---------------------")
print(5+np.ones((3,5)))

Matrix of 5's
---------------------
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [72]:
print("Empty matrix\n", np.empty((3,5))) # generates a random matrix for the given dimension and rows and columns

Empty matrix
 [[0.         0.         0.4472136  0.0531494  0.18257419]
 [0.4472136  0.2125976  0.36514837 0.4472136  0.4783446 ]
 [0.54772256 0.4472136  0.85039041 0.73029674 0.4472136 ]]


In [149]:
mat1 = np.eye(4) 
print("Identity matrix of dimension", mat1.shape)
print(mat1)

Identity matrix of dimension (4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [132]:
np.arange(3)

array([0, 1, 2])

In [80]:
np.arange(3.0)

array([0., 1., 2.])

In [81]:
 np.arange(3,7)

array([3, 4, 5, 6])

In [82]:
np.arange(3,7,2)

array([3, 5])

In [150]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [151]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [153]:
np.linspace(2.0, 3.0, num=9, retstep=True)

(array([2.   , 2.125, 2.25 , 2.375, 2.5  , 2.625, 2.75 , 2.875, 3.   ]), 0.125)

In [147]:
#Return numbers spaced evenly on a log scale.
np.linspace(2.0, 3.0, num=4)

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [154]:
np.logspace(2.0, 3.0, num=4,base = 10)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [113]:
np.logspace(2.0, 3.0, num=4, endpoint=False)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519])

In [155]:
np.logspace(2.0, 3.0, num=4, base=2.0)

array([4.        , 5.0396842 , 6.34960421, 8.        ])

## Reshaping

In [96]:
x = np.arange(16).reshape((4,4)) ## multiplication of arguments in reshape should match to the elements number
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [102]:
x = np.arange(16).reshape((-1,4)) ## system will take -1 as the rest of the shape, so here it indirectly means (4,4)
x

#### not only -1 , any -ve value will work as the same

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [103]:
y = np.arange(16).reshape((2,4,-1)) ## system will take -1 as the rest of the shape, so here it indirectly means (2,4,2)
y 

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

## Extract a diagonal or construct a diagonal array.

In [104]:
np.diag(x)

array([ 0,  5, 10, 15])

# 'K' means it leaves the no.of k columns and then takes the 1st square matrix from it.

In [110]:
np.diag(x, k=2) # leaves 2 columns from the right and then forms the matrix and gets the value

array([2, 7])

In [111]:
np.diag(x, k=-1)# # leaves 2 columns from the left and then forms the matrix and gets the value

array([ 4,  9, 14])

In [112]:
np.diag(np.diag(x))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [122]:
#Create a two-dimensional array with the flattened input as a diagonal.

In [113]:
np.diagflat([[1,2,3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [124]:
np.diagflat([1,2], 1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [125]:
#An array with ones at and below the given diagonal and zeros elsewhere.

In [116]:
np.tri(3, 3, 1, dtype=int)

array([[1, 1, 0],
       [1, 1, 1],
       [1, 1, 1]])

In [30]:
np.tri(3, 7,k=-1)

array([[0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0.]])

In [128]:
#return a Lower triangle of an array.

In [205]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], 0)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [130]:
#return Upper triangle of an array.

In [206]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0],
       [0, 0, 0]])

# Random number generation

## Uniform Distrubution : values between 0 to 1
## Normal Distrubution : values with Mean=0 and S.D=1

## Basically 3 types:
### random.rand -> values between 0 to 1 with Uniform Dist
### random.randn -> values with Normal Dist
### random.randint -> values between given range with shape of the matrix defined in the arguments

In [197]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

Random number generation (from Uniform distribution)
[[0.79234365 0.26636652 0.84876143]
 [0.78766627 0.06627396 0.8829639 ]]


In [209]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[ 0.08550888  0.73651756  0.08329424]
 [ 0.75179279  0.42441618  0.47752353]
 [ 0.23835886  1.06582108 -0.01790105]
 [ 0.48190152 -0.24940656 -0.44992115]]


In [120]:
np.arange(101,201).reshape(10,-1)

array([[101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
       [131, 132, 133, 134, 135, 136, 137, 138, 139, 140],
       [141, 142, 143, 144, 145, 146, 147, 148, 149, 150],
       [151, 152, 153, 154, 155, 156, 157, 158, 159, 160],
       [161, 162, 163, 164, 165, 166, 167, 168, 169, 170],
       [171, 172, 173, 174, 175, 176, 177, 178, 179, 180],
       [181, 182, 183, 184, 185, 186, 187, 188, 189, 190],
       [191, 192, 193, 194, 195, 196, 197, 198, 199, 200]])

In [121]:
print("Random integer vector:",np.random.randint(1,10)) #randint (low, high, # of samples to be drawn)

Random integer vector: 9


In [122]:
print ("\nRandom integer matrix")
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw


Random integer matrix
[[27 30 84 49]
 [82 33 59 88]
 [96 44 33 43]
 [81 13 48 86]]

20 samples drawn from a dice throw: [4 6 3 1 6 2 6 6 2 1 3 4 2 6 6 2 4 4 4 2]


# Reshaping

In [125]:
from numpy.random import randint as ri
a = ri(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,-19878)
c

array([[58,  2, 75, 29, 36],
       [47, 67, 23, 59,  2],
       [46, 67, 50,  8, 22],
       [96, 58, 36, 65, 46],
       [42, 65, 31,  2, 38],
       [12, 98, 16, 81, 15]])

In [126]:
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)


Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)


In [127]:
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)



a looks like
 -------------------- 
 [58  2 75 29 36 47 67 23 59  2 46 67 50  8 22 96 58 36 65 46 42 65 31  2
 38 12 98 16 81 15] 
 --------------------

b looks like
 -------------------- 
 [[[58  2 75 29 36]
  [47 67 23 59  2]
  [46 67 50  8 22]]

 [[96 58 36 65 46]
  [42 65 31  2 38]
  [12 98 16 81 15]]] 
 --------------------

c looks like
 -------------------- 
 [[58  2 75 29 36]
 [47 67 23 59  2]
 [46 67 50  8 22]
 [96 58 36 65 46]
 [42 65 31  2 38]
 [12 98 16 81 15]] 
 --------------------


## Sorting in Numpy

In [128]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))



Vector of random integers
 -------------------------------------------------- 
 [71 94 89 12 58 72 58 46 47 46]

Here is the sorted vector
 -------------------------------------------------- 
 [12 46 46 47 58 58 71 72 89 94]


In [129]:
M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
#print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=1, kind='mergesort'))
M


Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[14 43 69 86 98]
 [13 38 49 59 74]
 [26 31 49 67 83]
 [21 22 24 36 67]
 [14 31 64 73 81]]


array([[98, 14, 86, 43, 69],
       [38, 59, 13, 74, 49],
       [49, 83, 31, 26, 67],
       [36, 24, 67, 22, 21],
       [64, 31, 81, 14, 73]])

In [130]:
print("Max of a:", M.max())
print("Max of b:", b.max())
b

Max of a: 98
Max of b: 98


array([[[58,  2, 75, 29, 36],
        [47, 67, 23, 59,  2],
        [46, 67, 50,  8, 22]],

       [[96, 58, 36, 65, 46],
        [42, 65, 31,  2, 38],
        [12, 98, 16, 81, 15]]])

### if axis=1 in argmax() then it will return column indices which is highest in every row
### if axis = 0 then argmax() will return the highest index in the array

In [134]:
M

array([[98, 14, 86, 43, 69],
       [38, 59, 13, 74, 49],
       [49, 83, 31, 26, 67],
       [36, 24, 67, 22, 21],
       [64, 31, 81, 14, 73]])

In [132]:
b

array([[[58,  2, 75, 29, 36],
        [47, 67, 23, 59,  2],
        [46, 67, 50,  8, 22]],

       [[96, 58, 36, 65, 46],
        [42, 65, 31,  2, 38],
        [12, 98, 16, 81, 15]]])

In [136]:
c

array([[58,  2, 75, 29, 36],
       [47, 67, 23, 59,  2],
       [46, 67, 50,  8, 22],
       [96, 58, 36, 65, 46],
       [42, 65, 31,  2, 38],
       [12, 98, 16, 81, 15]])

In [135]:
print("Max of a location:", M.argmax(axis= 1 ))
print("Max of b location:", b.argmax())
print("Max of c location:", c.argmax())

Max of a location: [0 3 1 2 2]
Max of b location: 26
Max of c location: 26


# Indexing and slicing

In [139]:
arr = np.arange(0,11)
print("Array:",arr)


Array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [140]:
print("Element at 7th index is:", arr[7])


Element at 7th index is: 7


In [141]:
print("Elements from 3rd to 5th index are:", arr[3:6:2])


Elements from 3rd to 5th index are: [3 5]


In [142]:
print("Elements up to 4th index are:", arr[:4])
arr

Elements up to 4th index are: [0 1 2 3]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [143]:
print("Elements from last backwards are:", arr[-1:7:-1])


Elements from last backwards are: [10  9  8]


In [144]:
print("3 Elements from last backwards are:", arr[-1:-6:2])


3 Elements from last backwards are: []


In [145]:
arr = np.arange(0,21,2)
print("New array:",arr)


New array: [ 0  2  4  6  8 10 12 14 16 18 20]


In [146]:
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset

Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


In [38]:
import numpy as np 
from numpy.random import randint as ri
arr = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",arr)
#print(arr[0:4,2:5])
arr[0:3,[1,3]]

Matrix of random 2-digit numbers
--------------------------------
 [[75 18 90 74 64]
 [38 56 93 84 67]
 [97 18 79 28 84]]


array([[18, 74],
       [56, 84],
       [18, 28]])

In [160]:
print("\nDouble bracket indexing\n------------------------")
print("Element in row index 1 and column index 2:", arr[1][1])
arr


Double bracket indexing
------------------------
Element in row index 1 and column index 2: 90


array([[51, 42, 91, 33, 38],
       [54, 90, 82, 97, 31],
       [53, 54, 38, 99, 63]])

In [161]:
print("\nSingle bracket with comma indexing\n----------------------------------")
print("Element in row index 1 and column index 2:", arr[1,2])
print("\nRow or column extract\n----------------------")



Single bracket with comma indexing
----------------------------------
Element in row index 1 and column index 2: 82

Row or column extract
----------------------


In [162]:
print("Entire row at index 2:", arr[2])
print("Entire column at index 3:", arr[:,3])


Entire row at index 2: [53 54 38 99 63]
Entire column at index 3: [33 97 99]


In [163]:
print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", arr[1:3,3:5])



Subsetting sub-matrices
--------------------------
Matrix with row indices 1 and 2 and column indices 3 and 4
 [[97 31]
 [99 63]]


In [164]:
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", arr[0:2,[1,3]])

Matrix with row indices 0 and 1 and column indices 1 and 3
 [[42 33]
 [90 97]]


# Subseting

In [173]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat>50

Matrix of random 2-digit numbers
--------------------------------
 [[51 99 67 32 43]
 [53 61 80 97 51]
 [82 76 18 26 11]]


array([[ True,  True,  True, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True, False, False, False]])

In [174]:
print ("Elements greater than 50\n", mat[mat>50])

Elements greater than 50
 [51 99 67 53 61 80 97 51 82 76]


# Slicing

In [175]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)


Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [176]:
mat_slice = mat[:2,:2]
print ("\nSliced matrix")
print(mat_slice)
print ("\nChange the sliced matrix")


Sliced matrix
[[11 12]
 [21 22]]

Change the sliced matrix


In [18]:
mat_slice[0,0] = 1000
print (mat_slice)

[[1000   12]
 [  21   22]]


In [75]:
print("\nBut the original matrix? WHOA! It got changed too!")
print(mat)



But the original matrix? WHOA! It got changed too!
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [177]:
# Little different way to create a copy of the slixed matrix
print ("\nDoing it again little differently now...\n")
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)



Doing it again little differently now...

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [21]:
mat_slice = np.array(mat[:2,:2]) # Notice the np.array command to create a new array not just slicing
print ("\nSliced matrix")
print(mat_slice)



Sliced matrix
[[11 12]
 [21 22]]


In [178]:
print ("\nChange the sliced matrix")
mat_slice[0,0] = 1000
print (mat_slice)



Change the sliced matrix
[[1000   12]
 [  21   22]]


In [22]:
print("\nBut the original matrix? NO CHANGE this time:)")
print(mat)


But the original matrix? NO CHANGE this time:)
[[11 12 13]
 [21 22 23]
 [31 32 33]]


# Universal Functions

In [247]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)



1st Matrix of random single-digit numbers
----------------------------------------
 [[3 3 9]
 [6 1 8]
 [5 9 1]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[3 5 7]
 [4 4 9]
 [1 2 5]]


In [248]:
mat1*mat2

array([[ 9, 15, 63],
       [24,  4, 72],
       [ 5, 18,  5]])

# Actual Matrix multiplication

In [249]:
#print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1@mat2)



Multiplication
------------------
 [[ 30  45  93]
 [ 30  50  91]
 [ 52  63 121]]


In [251]:
print("\nDivision\n------------------\n", mat1/0)
#print("\nLineaer combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)



Division
------------------
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


/Users/sudhanshukumar/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [252]:
print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)



Addition of a scalar (100)
-------------------------
 [[103 103 109]
 [106 101 108]
 [105 109 101]]


In [253]:
print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n-------------------------------------------\n",pow(mat1,3))


Exponentiation, matrix cubed here
----------------------------------------
 [[ 27  27 729]
 [216   1 512]
 [125 729   1]]

Exponentiation, sq-root using pow function
-------------------------------------------
 [[ 27  27 729]
 [216   1 512]
 [125 729   1]]


# Broadcasting

In [174]:
#NumPy operations are usually done on pairs of arrays on an element-by-element basis. 
#In the simplest case, the two arrays must have exactly the same shape.
#NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. 
#When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing 
#dimensions, and works its way forward. Two dimensions are compatible when
#they are equal, or one of them is 1

In [254]:
start = np.zeros((4,4))
start= start+100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [256]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2,5])
print(add_rows)

[1 0 2 5]


In [257]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]]


In [262]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [263]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[100. 100. 100. 100.]
 [101. 101. 101. 101.]
 [102. 102. 102. 102.]
 [103. 103. 103. 103.]]


In [264]:
# this will just broadcast in both dimensions
add_scalar = np.array([100])  
print(start+y)

[[200. 200. 200. 200.]
 [201. 201. 201. 201.]
 [202. 202. 202. 202.]
 [203. 203. 203. 203.]]


# Array Math

In [265]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n------------\n",mat2)



1st Matrix of random single-digit numbers

 [[9 5 4]
 [1 7 3]
 [8 3 5]]

2nd Matrix of random single-digit numbers
------------
 [[4 8 6]
 [7 6 8]
 [4 6 5]]


In [266]:
print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))



Sq-root of 1st matrix using np
------------------
 [[3.         2.23606798 2.        ]
 [1.         2.64575131 1.73205081]
 [2.82842712 1.73205081 2.23606798]]


In [267]:
print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))



Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[8.10308393e+03 1.48413159e+02 5.45981500e+01]
 [2.71828183e+00 1.09663316e+03 2.00855369e+01]
 [2.98095799e+03 2.00855369e+01 1.48413159e+02]]


In [268]:
print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))
print(mat1)
print(mat2)


10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.95424251 0.69897    0.60205999]
 [0.         0.84509804 0.47712125]
 [0.90308999 0.47712125 0.69897   ]]
[[9 5 4]
 [1 7 3]
 [8 3 5]]
[[4 8 6]
 [7 6 8]
 [4 6 5]]


In [270]:
print("\nModulo reminder using np\n",'-'*50,"\n", np.fmod(mat1,mat2))
mat1%mat2


Modulo reminder using np
 -------------------------------------------------- 
 [[1 5 4]
 [1 1 3]
 [0 3 0]]


array([[1, 5, 4],
       [1, 1, 3],
       [0, 3, 0]])

In [186]:
print("\nCombination of functions by shwoing exponetial decay of a sine wave\n",'-'*70)



Combination of functions by shwoing exponetial decay of a sine wave
 ----------------------------------------------------------------------


In [207]:
A = np.linspace(0,12*np.pi,1001)


In [208]:
A

array([ 0.        ,  0.03769911,  0.07539822, ..., 37.62371362,
       37.66141273, 37.69911184])

# Class exam

In [75]:
(np.zeros((3,4,8)) + 5)*2

array([[[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]]])

In [76]:
np.linspace(4,8,80)

array([4.        , 4.05063291, 4.10126582, 4.15189873, 4.20253165,
       4.25316456, 4.30379747, 4.35443038, 4.40506329, 4.4556962 ,
       4.50632911, 4.55696203, 4.60759494, 4.65822785, 4.70886076,
       4.75949367, 4.81012658, 4.86075949, 4.91139241, 4.96202532,
       5.01265823, 5.06329114, 5.11392405, 5.16455696, 5.21518987,
       5.26582278, 5.3164557 , 5.36708861, 5.41772152, 5.46835443,
       5.51898734, 5.56962025, 5.62025316, 5.67088608, 5.72151899,
       5.7721519 , 5.82278481, 5.87341772, 5.92405063, 5.97468354,
       6.02531646, 6.07594937, 6.12658228, 6.17721519, 6.2278481 ,
       6.27848101, 6.32911392, 6.37974684, 6.43037975, 6.48101266,
       6.53164557, 6.58227848, 6.63291139, 6.6835443 , 6.73417722,
       6.78481013, 6.83544304, 6.88607595, 6.93670886, 6.98734177,
       7.03797468, 7.08860759, 7.13924051, 7.18987342, 7.24050633,
       7.29113924, 7.34177215, 7.39240506, 7.44303797, 7.49367089,
       7.5443038 , 7.59493671, 7.64556962, 7.69620253, 7.74683

In [78]:
l = [[1,2],[3,4]]
np.mat(l)

matrix([[1, 2],
        [3, 4]])

In [82]:
arr = np.ones((4,5,2))
arr
print(arr.ndim)
print(arr.dtype)
print(arr.shape)

3
float64
(4, 5, 2)


In [84]:
x1 = np.zeros((3,3,3))
x2 = np.ones((3,3,3))
x1+x2

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])